export function initialFieldValues(formKey) {
	const defaults = {
		contact: {
			firstname: '',
			lastname: '',
			email: '',
			phone: '',
			message: '',
		},
		scheduleAppointment: {
			firstname: '',
			lastname: '',
			email: '',
			phone: '',
			location: '',
			datetime: '',
			symptoms: '',
		},
		patientIntake: {
			firstname: '',
			lastname: '',
			phone: '',
			dateofbirth: '',
			email: '',
			address: '',
			city: '',
			apt: '',
			zipcode: '',
			state: '',
			may_contact_number: 'yes',
			may_contact_email: 'yes',
			may_forward_results: 'yes',
			declaration_agreed: false,
			terms_agreed: false,
			digital_signature: '',
		},
		covidScreening: {
			firstname: '',
			lastname: '',
			phone: '',
			dateofbirth: '',
			email: '',
			address: '',
			city: '',
			apt: '',
			zipcode: '',
			state: '',
			fever_or_chills: 'no',
			cough: 'no',
			difficulty_breathing: 'no',
			fatigue: 'no',
			headache: 'no',
			loss_of_taste_smell: 'no',
			sore_throat: 'no',
			congestion_runny_nose: 'no',
			covid_exposure: 'no',
			vaccination_status: 'not_vaccinated',
			previous_covid_infection: 'no',
			declaration_agreed: false,
			terms_agreed: false,
			digital_signature: '',
		},
		prescriptionConsent: {
			firstname: '',
			lastname: '',
			phone: '',
			dateofbirth: '',
			email: '',
			address: '',
			city: '',
			apt: '',
			zipcode: '',
			state: '',
			infection: '',
			takinganymedication: 'no',
			currentmedications: '',
			allergic_to_medication: 'no',
			allergies: '',
			pregnant_or_lactating: 'no',
			pharmacy_name: '',
			pharmacy_phonenumber: '',
			declaration_agreed: false,
			terms_agreed: false,
			digital_signature: '',
		},
	};

	return defaults[formKey] || {};
}
